version: '3'
services:
  users_db:
    build: ./users_db
    logging:
      driver: 'none'
    ports:
      - '3000:5984'

  files_db:
    build: ./files_db
      logging:
        driver: 'none'
      ports:
        - '3010:5984'

  user_ms:
    image: blinkbox/user-crud
    environment:
      DB_PORT: '5984'
      DB_URL: 'users_db'
    ports:
      - '4000:4000'
    links:
      - users_db

  auth_ms:
    image: blinkbox/authentication
    environment:
      DB_PORT: '5984'
      DB_URL: 'users_db'
      JWT_SECRET: 'ec6607e21b57ac2ccc5836754893ed33'
    ports:
      - '4005:4005'
    links:
      - users_db

  notification_ms:
    image: blinkbox/notification
    environment:
      NAME: "Blinkbox Project"
      USERNAME: "blinkboxunal@gmail.com"
      PASSWORD: "bl1nkb0x"
      EMAIL_SERVER: "smtp.gmail.com"
      PORT: '587'
    ports:
      - '4010:4010'

  update_ms:
    image: blinkbox/update
    environment:
      DB_PORT: '5984'
      DB_URL: 'files_db'
      SECRET_KEY_BASE: '88e17a0d8bc9aaff8b23b3a64921da46059b175d73966151dd10029934cde9d4fa645c55a2a8e71e4a23778e64ce408caf7c4e5ca7c163d3785c9363f1153e4d'
    command: bundle exec rails s -e production -p 4020 -b '0.0.0.0'
    volumes:
      - .:/update
    ports:
      - '4020:4020'
    links:
      - files_db

  delete_ms:
    image: blinkbox/delete
    environment:
      HOST_PORT: '4030'
      HOST_URL: '0.0.0.0'
      DB_URL: 'files_db'
      DB_PORT: '3010'
      DB_NAME: 'blinkbox_files'
    ports:
      - '4030:4030'
    links:
      - files_db

  upload_ms:
    image: blinkbox/upload
    environment:
      DB_PORT: '5984'
      DB_URL: 'files_db'
    ports:
      - '4015:4015'
    links:
      - files_db

  file_access_ms:
    image: blinkbox/fileaccess
    ports:
      - '4025:4025'
    environment:
      DB_NAME: 'blinkbox_files'
      DB_URL: 'files_db'
      DB_PORT: '5984'
      HOST_PORT: '4025'
      HOST_URL: '0.0.0.0'
    links:
      - files_db

  api_gateway:
    build: .
    environment:
      USER_PORT: '4000'
      USER_HOST: 'user_ms'
      AUTH_PORT: '4005'
      AUTH_HOST: 'auth_ms'
      NOTIFICATION_PORT: '4010'
      NOTIFICATION_HOST: 'notification_ms'
      UPDATE_PORT: '4020'
      UPDATE_HOST: 'update_ms'
      DELETE_PORT: '4030'
      DELETE_HOST: 'delete_ms'
      UPLOAD_PORT: '4015'
      UPLOAD_HOST: 'upload_ms'
      ACCESS_PORT: '4025'
      ACCESS_HOST: 'file_access_ms'
    ports:
      - '5000:5000'
    links:
      - user_ms
      - auth_ms
      - notification_ms
      - update_ms
      - delete_ms
      - upload_ms
      - file_access_ms