version: '2'
services:
  files_db:
    build: ./files_db
    logging:
      driver: 'none'
    ports:
      - '3010:5984'

  update_ms:
    image: blinkbox/update
    environment:
      DB_PORT: '5984'
      DB_URL: 'files_db'
      SECRET_KEY_BASE: '88e17a0d8bc9aaff8b23b3a64921da46059b175d73966151dd10029934cde9d4fa645c55a2a8e71e4a23778e64ce408caf7c4e5ca7c163d3785c9363f1153e4d'
    command: bundle exec rails s -e production -p 4020 -b '0.0.0.0'
    volumes:
      - .:/update
    ports:
      - '4020:4020'
    links:
      - files_db

  delete_ms:
    image: blinkbox/delete
    environment:
      HOST_PORT: '4030'
      HOST_URL: '0.0.0.0'
      DB_URL: 'files_db'
      DB_PORT: '3010'
      DB_NAME: 'blinkbox_files'
    ports:
      - '4030:4030'
    links:
      - files_db

  upload_ms:
    image: blinkbox/upload
    environment:
      DB_PORT: '5984'
      DB_URL: 'files_db'
    ports:
      - '4015:4015'
    links:
      - files_db

  file_access_ms:
    image: blinkbox/fileaccess
    ports:
      - '4025:4025'
    environment:
      DB_NAME: 'blinkbox_files'
      DB_URL: 'files_db'
      DB_PORT: '5984'
      HOST_PORT: '4025'
      HOST_URL: '0.0.0.0'
    links:
      - files_db