version: '3'
services:
  files_db:
    build: ./files_db
    logging:
          driver: 'none'
    ports:
      - '3010:5984'

  update_ms:
    image: blinkbox/update
    environment:
      DB_PORT: '5984'
      DB_URL: 'files_db'
      SECRET_KEY_BASE: '88e17a0d8bc9aaff8b23b3a64921da46059b175d73966151dd10029934cde9d4fa645c55a2a8e71e4a23778e64ce408caf7c4e5ca7c163d3785c9363f1153e4d'
    command: bundle exec rails s -e production -p 4020 -b '0.0.0.0'
    volumes:
      - .:/update
    ports:
      - '4020:4020'
    links:
      - files_db

  delete_ms:
    image: blinkbox/delete
    environment:
      HOST_PORT: '4030'
      HOST_URL: '0.0.0.0'
      DB_URL: 'files_db'
      DB_PORT: '3010'
      DB_NMA: 'blinkbox_files'
    ports:
      - '4030:4030'
    links:
      - files_db

  upload_ms:
    image: blinkbox/upload
    environment:
      DB_PORT: '5984'
      DB_URL: 'files_db'
    ports:
      - '4015:4015'
    links:
      - files_db

  api_gateway:
    build: .
    environment:
      UPDATE_PORT: '4020'
      UPDATE_HOST: 'update_ms'
      DELETE_PORT: '4030'
      DELETE_HOST: 'delete_ms'
      UPLOAD_PORT: '4015'
      UPLOAD_HOST: 'upload_ms'
    ports:
      - '5000:5000'
    links:
      - update_ms
      - delete_ms
      - upload_ms